targets:
  $default:
    builders:
      icon_class_generator|icon_font:
        enabled: true
builders:
  icon_font:
    import: 'package:icon_class_generator/builder.dart'
    builder_factories: ['iconFontBuilder']
    build_extensions: { '.dart': ['.g.part'] }
    auto_apply: root_package
    build_to: source
