targets:
  $default:
    builders:
      together_icons|icon_font:
        enabled: true
builders:
  icon_font:
    import: 'package:together_icons/builder.dart'
    builder_factories: ['iconFontBuilder']
    build_extensions: { '.dart': ['.g.part'] }
    auto_apply: root_package
    build_to: source
