name: icon_class_generator
description: A flexible icon package generator wit extended features.
version: 0.0.1-dev.3
homepage: https://moinsen.dev
repository: https://github.com/moinsen-dev/icon_class_generator
issue_tracker: https://github.com/moinsen-dev/icon_class_generator/issues

environment:
  sdk: '>=2.15.1 <3.0.0'
  flutter: '>=2.10.0'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter
  build: ^2.2.1
  source_gen: ^1.2.1
  recase: ^4.0.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  fonts:
    - family: Icon8
      fonts:
        - asset: lib/fonts/Icon8.ttf
    - family: LineIcons
      fonts:
        - asset: lib/fonts/LineIcons.ttf
