name: icon_class_generator
description: A Moinsen.dev Icon Package Generator
version: 0.0.1
homepage: together.moinsen.dev
publish_to: 'none'

environment:
  sdk: '>=2.15.1 <3.0.0'
  flutter: '>=2.10.0'

dependencies:
  flutter:
    sdk: flutter
  recase: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  source_gen: ^1.2.1
  build_runner: ^2.1.7

flutter:
  fonts:
    - family: Icon8
      fonts:
        - asset: lib/fonts/Icon8.ttf
    - family: LineIcons
      fonts:
        - asset: lib/fonts/LineIcons.ttf
