import 'package:flutter/material.dart';

class LineIcons {
  LineIcons._();

  static const _kFontFam = 'LineIcons';
  static const String? _kFontPkg = null;

  static const IconData add_files =
      IconData(0xea01, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData agenda =
      IconData(0xea02, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData px500 =
      IconData(0xea03, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarm =
      IconData(0xea04, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData amazon_original =
      IconData(0xea05, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adobe =
      IconData(0xea06, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airbnb =
      IconData(0xea07, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarm_clock =
      IconData(0xea08, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData amazon_pay =
      IconData(0xea09, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData amazon =
      IconData(0xea0a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ambulance =
      IconData(0xea0b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData amex =
      IconData(0xea0c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData anchor =
      IconData(0xea0d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData android_original =
      IconData(0xea0e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData android =
      IconData(0xea0f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angellist =
      IconData(0xea10, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_double_down =
      IconData(0xea11, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_double_left =
      IconData(0xea12, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_double_right =
      IconData(0xea13, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_double_up =
      IconData(0xea14, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angular =
      IconData(0xea15, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apartment =
      IconData(0xea16, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData app_store =
      IconData(0xea17, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple_music =
      IconData(0xea18, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple_pay =
      IconData(0xea19, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple =
      IconData(0xea1a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down_circle =
      IconData(0xea1b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down =
      IconData(0xea1c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left_circle =
      IconData(0xea1d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left =
      IconData(0xea1e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archive =
      IconData(0xea1f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_circle =
      IconData(0xea20, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right =
      IconData(0xea21, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_top_left =
      IconData(0xea22, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_top_right =
      IconData(0xea23, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up_circle =
      IconData(0xea24, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up =
      IconData(0xea25, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrows_horizontal =
      IconData(0xea26, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrows_vertical =
      IconData(0xea27, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData atlassian =
      IconData(0xea28, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aws =
      IconData(0xea29, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData azure =
      IconData(0xea2a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backward =
      IconData(0xea2b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baloon =
      IconData(0xea2c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ban =
      IconData(0xea2d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bar_chart =
      IconData(0xea2e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basketball =
      IconData(0xea2f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData behance_original =
      IconData(0xea30, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData behance =
      IconData(0xea31, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bi_cycle =
      IconData(0xea32, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bitbucket =
      IconData(0xea33, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bitcoin =
      IconData(0xea34, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blackboard =
      IconData(0xea35, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blogger =
      IconData(0xea36, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bluetooth_original =
      IconData(0xea37, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bluetooth =
      IconData(0xea38, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bold =
      IconData(0xea39, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bolt_alt =
      IconData(0xea3a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book =
      IconData(0xea3b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_alt =
      IconData(0xea3c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark =
      IconData(0xea3d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bootstrap =
      IconData(0xea3e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bricks =
      IconData(0xea3f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bolt =
      IconData(0xea40, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bridge =
      IconData(0xea41, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefcase =
      IconData(0xea42, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brush_alt =
      IconData(0xea43, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brush =
      IconData(0xea44, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btc =
      IconData(0xea45, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bubble =
      IconData(0xea46, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bug =
      IconData(0xea47, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bulb =
      IconData(0xea48, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bullhorn =
      IconData(0xea49, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData burger =
      IconData(0xea4a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus =
      IconData(0xea4b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cake =
      IconData(0xea4c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calculator =
      IconData(0xea4d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar =
      IconData(0xea4e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera =
      IconData(0xea4f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData candy_cane =
      IconData(0xea50, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData candy =
      IconData(0xea51, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData capsule =
      IconData(0xea52, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_alt =
      IconData(0xea53, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car =
      IconData(0xea54, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caravan =
      IconData(0xea55, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_full =
      IconData(0xea56, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart =
      IconData(0xea57, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData certificate =
      IconData(0xea58, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_box =
      IconData(0xea59, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkmark_circle =
      IconData(0xea5a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkmark =
      IconData(0xea5b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chef_hat =
      IconData(0xea5c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_down_circle =
      IconData(0xea5d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_down =
      IconData(0xea5e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_left_circle =
      IconData(0xea5f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_left =
      IconData(0xea60, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right_circle =
      IconData(0xea61, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right =
      IconData(0xea62, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_up_circle =
      IconData(0xea63, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_up =
      IconData(0xea64, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chrome =
      IconData(0xea65, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chromecast =
      IconData(0xea66, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_minus =
      IconData(0xea67, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_plus =
      IconData(0xea68, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard =
      IconData(0xea69, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close =
      IconData(0xea6a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_check =
      IconData(0xea6b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_download =
      IconData(0xea6c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_network =
      IconData(0xea6d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_sync =
      IconData(0xea6e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_upload =
      IconData(0xea6f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud =
      IconData(0xea70, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloudflare =
      IconData(0xea71, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloudy_sun =
      IconData(0xea72, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code_alt =
      IconData(0xea73, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code =
      IconData(0xea74, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codepen =
      IconData(0xea75, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coffee_cup =
      IconData(0xea76, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog =
      IconData(0xea77, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cogs =
      IconData(0xea78, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coin =
      IconData(0xea79, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comments_alt =
      IconData(0xea7a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comments_reply =
      IconData(0xea7b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comments =
      IconData(0xea7c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compass =
      IconData(0xea7d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData connectdevelop =
      IconData(0xea7e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData construction_hammer =
      IconData(0xea7f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData construction =
      IconData(0xea80, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData consulting =
      IconData(0xea81, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control_panel =
      IconData(0xea82, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cool =
      IconData(0xea83, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cpanel =
      IconData(0xea84, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData creative_commons =
      IconData(0xea85, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_cards =
      IconData(0xea86, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crop =
      IconData(0xea87, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross_circle =
      IconData(0xea88, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crown =
      IconData(0xea89, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData css3 =
      IconData(0xea8a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cup =
      IconData(0xea8b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customer =
      IconData(0xea8c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cut =
      IconData(0xea8d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard =
      IconData(0xea8e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData database =
      IconData(0xea8f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delivery =
      IconData(0xea90, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dev =
      IconData(0xea91, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamond_alt =
      IconData(0xea92, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamond =
      IconData(0xea93, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData digitalocean =
      IconData(0xea94, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diners_club =
      IconData(0xea95, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dinner =
      IconData(0xea96, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direction_alt =
      IconData(0xea97, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direction_ltr =
      IconData(0xea98, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direction_rtl =
      IconData(0xea99, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direction =
      IconData(0xea9a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discord =
      IconData(0xea9b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discover =
      IconData(0xea9c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData display_alt =
      IconData(0xea9d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData display =
      IconData(0xea9e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData docker =
      IconData(0xea9f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar =
      IconData(0xeaa0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData domain =
      IconData(0xeaa1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download =
      IconData(0xeaa2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dribbble =
      IconData(0xeaa3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drop =
      IconData(0xeaa4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dropbox_original =
      IconData(0xeaa5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dropbox =
      IconData(0xeaa6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drupal_original =
      IconData(0xeaa7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drupal =
      IconData(0xeaa8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell =
      IconData(0xeaa9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edge =
      IconData(0xeaaa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData empty_file =
      IconData(0xeaab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData enter =
      IconData(0xeaac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envato =
      IconData(0xeaad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope =
      IconData(0xeaae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eraser =
      IconData(0xeaaf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData euro =
      IconData(0xeab0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exit_down =
      IconData(0xeab1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exit_up =
      IconData(0xeab2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exit =
      IconData(0xeab3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye =
      IconData(0xeab4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_filled =
      IconData(0xeab5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_messenger =
      IconData(0xeab6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_original =
      IconData(0xeab7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_oval =
      IconData(0xeab8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook =
      IconData(0xeab9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData figma =
      IconData(0xeaba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData files =
      IconData(0xeabb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData firefox_original =
      IconData(0xeabc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData firefox =
      IconData(0xeabd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fireworks =
      IconData(0xeabe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData first_aid =
      IconData(0xeabf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag_alt =
      IconData(0xeac0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag =
      IconData(0xeac1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flags =
      IconData(0xeac2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flickr =
      IconData(0xeac3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flower =
      IconData(0xeac4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder =
      IconData(0xeac5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward =
      IconData(0xeac6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frame_expand =
      IconData(0xeac7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fresh_juice =
      IconData(0xeac8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData friendly =
      IconData(0xeac9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData full_screen =
      IconData(0xeaca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData funnel =
      IconData(0xeacb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery =
      IconData(0xeacc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData game =
      IconData(0xeacd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gatsby =
      IconData(0xeace, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift =
      IconData(0xeacf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData git =
      IconData(0xead0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_original =
      IconData(0xead1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github =
      IconData(0xead2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData goodreads =
      IconData(0xead3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_drive =
      IconData(0xead4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_pay =
      IconData(0xead5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_wallet =
      IconData(0xead6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google =
      IconData(0xead7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graduation =
      IconData(0xead8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graph =
      IconData(0xead9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid_alt =
      IconData(0xeada, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid =
      IconData(0xeadb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grow =
      IconData(0xeadc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hacker_news =
      IconData(0xeadd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hammer =
      IconData(0xeade, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hand =
      IconData(0xeadf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData handshake =
      IconData(0xeae0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData happy =
      IconData(0xeae1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData harddrive =
      IconData(0xeae2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData headphone_alt =
      IconData(0xeae3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData headphone =
      IconData(0xeae4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_filled =
      IconData(0xeae5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_monitor =
      IconData(0xeae6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart =
      IconData(0xeae7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData helicopter =
      IconData(0xeae8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData helmet =
      IconData(0xeae9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help =
      IconData(0xeaea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData highlight_alt =
      IconData(0xeaeb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData highlight =
      IconData(0xeaec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home =
      IconData(0xeaed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hospital =
      IconData(0xeaee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass =
      IconData(0xeaef, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData html5 =
      IconData(0xeaf0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image =
      IconData(0xeaf1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData imdb =
      IconData(0xeaf2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox =
      IconData(0xeaf3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData indent_decrease =
      IconData(0xeaf4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData indent_increase =
      IconData(0xeaf5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData infinite =
      IconData(0xeaf6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information =
      IconData(0xeaf7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram_filled =
      IconData(0xeaf8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram_original =
      IconData(0xeaf9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram =
      IconData(0xeafa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData invention =
      IconData(0xeafb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData invest_monitor =
      IconData(0xeafc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData investment =
      IconData(0xeafd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData island =
      IconData(0xeafe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData italic =
      IconData(0xeaff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData java =
      IconData(0xeb00, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData javascript =
      IconData(0xeb01, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jcb =
      IconData(0xeb02, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData joomla_original =
      IconData(0xeb03, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData joomla =
      IconData(0xeb04, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jsfiddle =
      IconData(0xeb05, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData juice =
      IconData(0xeb06, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key =
      IconData(0xeb07, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard =
      IconData(0xeb08, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyword_research =
      IconData(0xeb09, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop_phone =
      IconData(0xeb0a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop =
      IconData(0xeb0b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laravel =
      IconData(0xeb0c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layers =
      IconData(0xeb0d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layout =
      IconData(0xeb0e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leaf =
      IconData(0xeb0f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData library_icon =
      IconData(0xeb10, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData license =
      IconData(0xeb11, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lifering =
      IconData(0xeb12, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData line_dashed =
      IconData(0xeb13, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData line_dotted =
      IconData(0xeb14, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData line_double =
      IconData(0xeb15, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData line_spacing =
      IconData(0xeb16, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData line =
      IconData(0xeb17, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lineicons_alt =
      IconData(0xeb18, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lineicons =
      IconData(0xeb19, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link =
      IconData(0xeb1a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin_original =
      IconData(0xeb1b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin =
      IconData(0xeb1c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list =
      IconData(0xeb1d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_alt =
      IconData(0xeb1e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock =
      IconData(0xeb1f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magento =
      IconData(0xeb20, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnet =
      IconData(0xeb21, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnifier =
      IconData(0xeb22, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mailchimp =
      IconData(0xeb23, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_marker =
      IconData(0xeb24, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map =
      IconData(0xeb25, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData markdown =
      IconData(0xeb26, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mashroom =
      IconData(0xeb27, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mastercard =
      IconData(0xeb28, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medium =
      IconData(0xeb29, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu =
      IconData(0xeb2a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic =
      IconData(0xeb2b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microphone =
      IconData(0xeb2c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microscope =
      IconData(0xeb2d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microsoft_edge =
      IconData(0xeb2e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microsoft =
      IconData(0xeb2f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus =
      IconData(0xeb30, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile =
      IconData(0xeb31, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_location =
      IconData(0xeb32, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_protection =
      IconData(0xeb33, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_alt =
      IconData(0xeb34, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more =
      IconData(0xeb35, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mouse =
      IconData(0xeb36, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData move =
      IconData(0xeb37, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music =
      IconData(0xeb38, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData netlify =
      IconData(0xeb39, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData network =
      IconData(0xeb3a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData night =
      IconData(0xeb3b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nodejs_alt =
      IconData(0xeb3c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nodejs =
      IconData(0xeb3d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notepad =
      IconData(0xeb3e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData npm =
      IconData(0xeb3f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData offer =
      IconData(0xeb40, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData opera =
      IconData(0xeb41, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData package =
      IconData(0xeb42, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData page_break =
      IconData(0xeb43, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pagination =
      IconData(0xeb44, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paint_bucket =
      IconData(0xeb45, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paint_roller =
      IconData(0xeb46, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pallet =
      IconData(0xeb47, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paperclip =
      IconData(0xeb48, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData patreon =
      IconData(0xeb49, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause =
      IconData(0xeb4a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paypal_original =
      IconData(0xeb4b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paypal =
      IconData(0xeb4c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_alt =
      IconData(0xeb4d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil =
      IconData(0xeb4e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_set =
      IconData(0xeb4f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone =
      IconData(0xeb50, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData php =
      IconData(0xeb51, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pie_chart =
      IconData(0xeb52, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pilcrow =
      IconData(0xeb53, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin =
      IconData(0xeb54, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pinterest =
      IconData(0xeb55, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pizza =
      IconData(0xeb56, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plane =
      IconData(0xeb57, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_store =
      IconData(0xeb58, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play =
      IconData(0xeb59, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playstation =
      IconData(0xeb5a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plug =
      IconData(0xeb5b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus =
      IconData(0xeb5c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pointer_down =
      IconData(0xeb5d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pointer_left =
      IconData(0xeb5e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pointer_right =
      IconData(0xeb5f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pointer_top =
      IconData(0xeb60, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pointer =
      IconData(0xeb61, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData popup =
      IconData(0xeb62, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData postcard =
      IconData(0xeb63, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pound =
      IconData(0xeb64, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData power_switch =
      IconData(0xeb65, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData printer =
      IconData(0xeb66, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData producthunt =
      IconData(0xeb67, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData protection =
      IconData(0xeb68, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pulse =
      IconData(0xeb69, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pyramids =
      IconData(0xeb6a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData python =
      IconData(0xeb6b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question_circle =
      IconData(0xeb6c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quora =
      IconData(0xeb6d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quotation =
      IconData(0xeb6e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radio_button =
      IconData(0xeb6f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rain =
      IconData(0xeb70, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reddit =
      IconData(0xeb71, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reload =
      IconData(0xeb72, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData react =
      IconData(0xeb73, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remove_file =
      IconData(0xeb74, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reply =
      IconData(0xeb75, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData restaurant =
      IconData(0xeb76, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData revenue =
      IconData(0xeb77, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData road =
      IconData(0xeb78, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rocket =
      IconData(0xeb79, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rss_feed =
      IconData(0xeb7a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ruler_alt =
      IconData(0xeb7b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ruler_pencil =
      IconData(0xeb7c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ruler =
      IconData(0xeb7d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rupee =
      IconData(0xeb7e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sad =
      IconData(0xeb7f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save =
      IconData(0xeb80, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData school_bench_alt =
      IconData(0xeb81, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData school_bench =
      IconData(0xeb82, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scooter =
      IconData(0xeb83, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scroll_down =
      IconData(0xeb84, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_alt =
      IconData(0xeb85, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search =
      IconData(0xeb86, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData select =
      IconData(0xeb87, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seo =
      IconData(0xeb88, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData service =
      IconData(0xeb89, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_alt_1 =
      IconData(0xeb8a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_alt =
      IconData(0xeb8b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share =
      IconData(0xeb8c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield =
      IconData(0xeb8d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shift_left =
      IconData(0xeb8e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shift_right =
      IconData(0xeb8f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ship =
      IconData(0xeb90, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopify =
      IconData(0xeb91, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_basket =
      IconData(0xeb92, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shortcode =
      IconData(0xeb93, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shovel =
      IconData(0xeb94, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shuffle =
      IconData(0xeb95, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal =
      IconData(0xeb96, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sketch =
      IconData(0xeb97, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skipping_rope =
      IconData(0xeb98, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skype =
      IconData(0xeb99, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slack_line =
      IconData(0xeb9a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slack =
      IconData(0xeb9b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slice =
      IconData(0xeb9c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slideshare =
      IconData(0xeb9d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slim =
      IconData(0xeb9e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smile =
      IconData(0xeb9f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snapchat =
      IconData(0xeba0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_alpha_asc =
      IconData(0xeba1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_amount_asc =
      IconData(0xeba2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_amount_dsc =
      IconData(0xeba3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soundcloud_original =
      IconData(0xeba4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soundcloud =
      IconData(0xeba5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speechless =
      IconData(0xeba6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spellcheck =
      IconData(0xeba7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spinner_arrow =
      IconData(0xeba8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spinner_solid =
      IconData(0xeba9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spinner =
      IconData(0xebaa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spotify_original =
      IconData(0xebab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spotify =
      IconData(0xebac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spray =
      IconData(0xebad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sprout =
      IconData(0xebae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData squarespace =
      IconData(0xebaf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stackoverflow =
      IconData(0xebb0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stamp =
      IconData(0xebb1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_empty =
      IconData(0xebb2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_filled =
      IconData(0xebb3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_half =
      IconData(0xebb4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star =
      IconData(0xebb5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stats_down =
      IconData(0xebb6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stats_up =
      IconData(0xebb7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData steam =
      IconData(0xebb8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sthethoscope =
      IconData(0xebb9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop =
      IconData(0xebba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData strikethrough =
      IconData(0xebbb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stripe =
      IconData(0xebbc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stumbleupon =
      IconData(0xebbd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun =
      IconData(0xebbe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData support =
      IconData(0xebbf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData surf_board =
      IconData(0xebc0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData suspect =
      IconData(0xebc1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swift =
      IconData(0xebc2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData syringe =
      IconData(0xebc3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tab =
      IconData(0xebc4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag =
      IconData(0xebc5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData target_customer =
      IconData(0xebc6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData target_revenue =
      IconData(0xebc7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData target =
      IconData(0xebc8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taxi =
      IconData(0xebc9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData teabag =
      IconData(0xebca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telegram_original =
      IconData(0xebcb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telegram =
      IconData(0xebcc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_align_center =
      IconData(0xebcd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_align_justify =
      IconData(0xebce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_align_left =
      IconData(0xebcf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_align_right =
      IconData(0xebd0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_format =
      IconData(0xebd1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thought =
      IconData(0xebd2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_down =
      IconData(0xebd3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_format_remove =
      IconData(0xebd4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up =
      IconData(0xebd5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thunder_alt =
      IconData(0xebd6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thunder =
      IconData(0xebd7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket_alt =
      IconData(0xebd8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket =
      IconData(0xebd9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tiktok =
      IconData(0xebda, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timer =
      IconData(0xebdb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tounge =
      IconData(0xebdc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData train_alt =
      IconData(0xebdd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData train =
      IconData(0xebde, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_can =
      IconData(0xebdf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData travel =
      IconData(0xebe0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tree =
      IconData(0xebe1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trees =
      IconData(0xebe2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trello =
      IconData(0xebe3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trowel =
      IconData(0xebe4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tshirt =
      IconData(0xebe5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tumblr =
      IconData(0xebe6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitch =
      IconData(0xebe7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter_filled =
      IconData(0xebe8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter_original =
      IconData(0xebe9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter =
      IconData(0xebea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ubuntu =
      IconData(0xebeb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData underline =
      IconData(0xebec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlink =
      IconData(0xebed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlock =
      IconData(0xebee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unsplash =
      IconData(0xebef, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload =
      IconData(0xebf0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user =
      IconData(0xebf1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ux =
      IconData(0xebf2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector =
      IconData(0xebf3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video =
      IconData(0xebf4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vimeo =
      IconData(0xebf5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users =
      IconData(0xebf6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visa =
      IconData(0xebf7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vk =
      IconData(0xebf8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_high =
      IconData(0xebf9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_low =
      IconData(0xebfa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_medium =
      IconData(0xebfb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_mute =
      IconData(0xebfc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume =
      IconData(0xebfd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet =
      IconData(0xebfe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning =
      IconData(0xebff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData website_alt =
      IconData(0xec00, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData website =
      IconData(0xec01, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wechat =
      IconData(0xec02, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weight =
      IconData(0xec03, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp =
      IconData(0xec04, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wheelbarrow =
      IconData(0xec05, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wheelchair =
      IconData(0xec06, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData windows =
      IconData(0xec07, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wordpress_filled =
      IconData(0xec08, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wordpress =
      IconData(0xec09, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData world_alt =
      IconData(0xec0a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData write =
      IconData(0xec0b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData world =
      IconData(0xec0c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xbox =
      IconData(0xec0d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yahoo =
      IconData(0xec0e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ycombinator =
      IconData(0xec0f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yen =
      IconData(0xec10, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zip =
      IconData(0xec11, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_in =
      IconData(0xec12, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube =
      IconData(0xec13, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_out =
      IconData(0xec14, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
